# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 247205257668a6d5be4b3db2cbbe6fa572640721ba5e2bc70b391c3e483d751dc2d6fcbd919deea7b90f2b4e7baafd2ecbb79677041af91058bcf0f2015bcbb5

test:
  secret_key_base: 8b6b748238cdbed87c90cbd00758639bb579b4697532caa2c0b25d95f260405c95e74b85a270b221153a5bae627289a71b0f04cd2baf38e86e7ab927a217ed9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
